---

name: Trigger qmd-progress CI
on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  trigger_qmd_CI:
    name: Trigger qmd-progress CI
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'lanl/bml' }}
    steps:
      - run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token x${WORKFLOW_TOKEN}" \
            -d '{"event_type":"bml_update"}' \
            https://api.github.com/repos/lanl/qmd-progress/dispatches
